name: Deploy to SFTP
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: sftp-deploy
      url: https://github.com
    strategy:
      matrix:
        go-version: ['1.21.x']
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build Go application
        run: go build -o CHANGE_ME main.go

      - name: Deploy to SFTP
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local_path: './app/*'
          remote_path: '.'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}
        run: echo $username@$server:$port ___ $password

      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local_path: './app/*'
          remote_path: '.'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}
